### ISSUE TITLE
Participant Search function not working after data change

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/dashboard#371]
Participant search function is not finding participant after a change to the data. For example if the site study managers change the last name in the Participant Details page and then try to search for the participant with last name, the search will not find the participant. (The participant can still be searched successfully by non-changed name or DOB and Connect ID, study ID, token).

**Comment by abhinavjonnada82** [comment]
Done.

**Comment by brotzmanmj** [comment]
@abhinavjonnada82 The HF team tried searching the participant with changed last name again in the biospecimen dashboard and it still doesn't work.

**Comment by brotzmanmj** [comment]
Abhinav stated it will work only for new participants, not for already existing ones. HF is doing a test now with a new pt in dev.
